### ISSUE TITLE
Add the Enter A New Task  feature to the Timer

### ISSUE THREAD

**Issue by TheOpenInnovator** [TheOpenInnovator/Productivity-Tracker#10]
The current version doesn't have the functionality to add a new task to the timer section.
- It's only accepting the tasks from the check list section only through **Map All Button**  & not even from the **Custom Map Button**
- So Add a new Functionality in the Timer Section to Provide the user to enter a new task in the Timer section directly apart from the Map all option from the Checklist section.
- Make sure the Map all feature or choosing the tasks from the dropdown option which is currently present is not removed, but the feature mentioned in the current issue is added additionally to the current version.
- Fix the Animation of the Timer Present Below. Make it professional and premium with only necessary animation if required.
- The current versions of the Timer section is attached below.
**Light Theme :** 
![image](https://github.com/user-attachments/assets/64d7a97e-0eaa-4a47-9d4b-cb343110c9bb)

**Dark Theme :** 
![image](https://github.com/user-attachments/assets/551836f4-ec23-4d29-b1dc-16f5dfe70b24)

**Instructions :**

- Make sure to mention in detail what all changes or enhancements you have made in the PR
- Provide the Screen shots of the changes implemented.
- Make sure the changes made are compatible on all screen sizes and devices and are professional to use.
- Resolve any conflicts in the code by checking once the PR is generated.

**Comment by Mukku27** [comment]
@TheOpenInnovator  Assign this issue to me and specify requirements(if any )
