### ISSUE TITLE
Enhance the Alert Message 

### ISSUE THREAD

**Issue by TheOpenInnovator** [TheOpenInnovator/Productivity-Tracker#11]
The current version of the website, doesn't have proper Alert messages.
- Go through each and every functionality and add the proper Alert message with appropriate message & appropriate styling of the respective to the functionality of that feature.
- Feel free to reach out for any queries.

**Instructions :**

- Make sure to mention in detail what all changes or enhancements you have made in the PR
- Provide the Screen shots of the changes implemented.
- Make sure the changes made are compatible on all screen sizes and devices and are professional to use.
- Resolve any conflicts in the code by checking once the PR is generated.

**Comment by gt951436** [comment]
@TheOpenInnovator 
do you want message like when we hover over a functionality and it shows a message about the functionality? or anything else?

**Comment by gt951436** [comment]
please clarify the doubts and assign this task to me. @TheOpenInnovator

**Comment by TheOpenInnovator** [comment]
Hey @gt951436  Pls add some note in this website : https://theopeninnovator.github.io/Zen-Note/ and try to **delete** the entered Note. Then an Alert Message will generate.

Based on that create similar kind of alert messages for this Productivity for whichever functionality required with proper styling and sizes. Make sure to add any functionality or other  changes which can make the overall website better and interactive.

Feel free to reach out  for any queries.
