### ISSUE TITLE
Dark Mode Setting Not Persisting After Page Refresh

### ISSUE THREAD

**Issue by Sakyasekhar** [TheOpenInnovator/Productivity-Tracker#13]
When a user enables dark mode, the website switches to the dark theme as expected. However, the dark mode setting does not persist after a page refresh, causing the site to revert back to the default light mode. This behavior affects user experience, as users need to re-enable dark mode after each refresh.

**Steps to Reproduce:**
1. Navigate to the website.
2. Enable dark mode using the toggle switch.
3. Refresh the page.
4. Observe that the site reverts back to light mode instead of retaining the dark mode setting.

**Expected Behavior:**  
The dark mode setting should be remembered even after a page refresh, so the website remains in dark mode if it was enabled previously.

**Actual Behavior:**  
The website resets to light mode on page refresh, regardless of the user’s previous dark mode selection.

**Suggested Solution:**  
Store the dark mode preference in the user's local storage or cookies. On page load, check for the stored preference and apply the appropriate theme based on the saved setting.

**Request:**  
@TheOpenInnovator , could you please assign this issue to me? I would be happy to work on it and implement the solution.

**Comment by TheOpenInnovator** [comment]
Hey @Sakyasekhar The issue has been assigned to you. You can start working on it.

**Comment by Sakyasekhar** [comment]
@TheOpenInnovator I have made the PR, please check it.

**Comment by Sakyasekhar** [comment]
Hi @TheOpenInnovator,

Thank you for assigning the issue to me. I have already submitted a pull request (PR), but it seems that after my PR, another PR from @Mukku27 was merged, which also addresses the dark mode issue and has caused conflicts with my PR.

I’ve resolved the conflicts and updated my PR, but I wanted to make sure you’re aware of the situation before proceeding.

Looking forward to your guidance on how we should move forward. Thanks again!

**Comment by TheOpenInnovator** [comment]
Hey @Sakyasekhar  We have something for you under the PR #16 . Please do check and hope you start working on it.

**Comment by Sakyasekhar** [comment]
@TheOpenInnovator , I fixed it just now, check it out.

**Comment by TheOpenInnovator** [comment]
Congratulations @Sakyasekhar Your PR has been merged.
