### ISSUE TITLE
Signup and SignIn for tracking the progress

### ISSUE THREAD

**Issue by pavankotti** [TheOpenInnovator/Productivity-Tracker#19]
would like to add user simple authentication using clerk

**Comment by sikehish** [comment]
I'd like to take this up. What exactly are you looking for in auth? Oauth or just email based auth?

**Comment by pavan25022005** [comment]
I added this issue to take this task up.

**Comment by TheOpenInnovator** [comment]
![image](https://github.com/user-attachments/assets/6cacd12f-3eff-4c39-922c-38e1bd8122a0)
![image](https://github.com/user-attachments/assets/345cd8a7-a5bf-4b03-897c-f43aeee3c1d2)
H
![image](https://github.com/user-attachments/assets/f4d58ba0-e779-44f6-9a84-f77b14370529)

**Comment by TheOpenInnovator** [comment]
Hey @pavan25022005 You can start working on this issue.  Do mention all the changes & implementations you have made in the PR along with the screenshots.

**Comment by TheOpenInnovator** [comment]
Hey @sikehish  You can create a new issue by going through the website related to the reports. The website needs to display reports based on various data collected from the user on a daily  basis by tracking all his activities through detailed reports.  

Try to raise a PR on this issue with all the implementations required for this website. Make sure to mention all the improvements you have done and also do attach the screenshots of the changes.

Feel free to reach out for any queries.
